# SPDX-FileCopyrightText: 2024 Benedikt Franke <benedikt.franke@dlr.de>
# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
#
# SPDX-License-Identifier: Apache-2.0

services:
  web:
    image: ghcr.io/dlr-ki/fl-demonstrator-django:main
    #image: local/fl-demonstrator-django:latest
    #build:
    #  context: ../fl-demonstrator
    #  dockerfile: ../fl-demonstrator/docker/django/Dockerfile
    container_name: web
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - server.env
    networks:
      - mnist-demo

  celery:
    image: ghcr.io/dlr-ki/fl-demonstrator-celery:main
    #image: local/fl-demonstrator-celery:latest
    #build:
    #  context: ../fl-demonstrator
    #  dockerfile: ../fl-demonstrator/docker/celery/Dockerfile
    container_name: celery
    restart: always
    depends_on:
      - redis
    env_file:
      - server.env
    networks:
      - mnist-demo

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - mnist-demo

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - server.env
    networks:
      - mnist-demo

  s3:
    image: quay.io/minio/minio
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    env_file:
      - server.env
    networks:
      - mnist-demo
    volumes:
      - s3data:/data


networks:
  mnist-demo:
    external: true

volumes:
  s3data:
